/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bienvenidaAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/bienvenidaSocio`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/eventos/crear`; params?: Router.UnknownInputParams; } | { pathname: `/eventos/editar`; params?: Router.UnknownInputParams; } | { pathname: `/eventos`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones/crear`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones/editar`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones/crear`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones/editar`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/socios/crear`; params?: Router.UnknownInputParams; } | { pathname: `/socios`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/socios/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/socios/[id]/editar`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bienvenidaAdmin`; params?: Router.UnknownOutputParams; } | { pathname: `/bienvenidaSocio`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/eventos/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/eventos/editar`; params?: Router.UnknownOutputParams; } | { pathname: `/eventos`; params?: Router.UnknownOutputParams; } | { pathname: `/localizaciones/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/localizaciones/editar`; params?: Router.UnknownOutputParams; } | { pathname: `/localizaciones`; params?: Router.UnknownOutputParams; } | { pathname: `/notificaciones/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/notificaciones/editar`; params?: Router.UnknownOutputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownOutputParams; } | { pathname: `/socios/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/socios`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/socios/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/socios/[id]/editar`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/bienvenidaAdmin${`?${string}` | `#${string}` | ''}` | `/bienvenidaSocio${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/eventos/crear${`?${string}` | `#${string}` | ''}` | `/eventos/editar${`?${string}` | `#${string}` | ''}` | `/eventos${`?${string}` | `#${string}` | ''}` | `/localizaciones/crear${`?${string}` | `#${string}` | ''}` | `/localizaciones/editar${`?${string}` | `#${string}` | ''}` | `/localizaciones${`?${string}` | `#${string}` | ''}` | `/notificaciones/crear${`?${string}` | `#${string}` | ''}` | `/notificaciones/editar${`?${string}` | `#${string}` | ''}` | `/notificaciones${`?${string}` | `#${string}` | ''}` | `/socios/crear${`?${string}` | `#${string}` | ''}` | `/socios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bienvenidaAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/bienvenidaSocio`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/eventos/crear`; params?: Router.UnknownInputParams; } | { pathname: `/eventos/editar`; params?: Router.UnknownInputParams; } | { pathname: `/eventos`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones/crear`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones/editar`; params?: Router.UnknownInputParams; } | { pathname: `/localizaciones`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones/crear`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones/editar`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/socios/crear`; params?: Router.UnknownInputParams; } | { pathname: `/socios`; params?: Router.UnknownInputParams; } | `/+not-found` | `/socios/${Router.SingleRoutePart<T>}` | `/socios/${Router.SingleRoutePart<T>}/editar` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/socios/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/socios/[id]/editar`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
